name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Start Jitpack Build
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://jitpack.io/com/github/ktlib-org/web/${{ steps.tag_version.outputs.new_tag }}/web-${{ steps.tag_version.outputs.new_tag }}.pom
          method: 'GET'
          preventFailureOnNoResponse: false
          retry: 10
          retryWait: 20000

